import {slots,bounds,hour,parse,baseDoctor,validateCoverage} from './scheduling.js';
export function coverageUI(root,storage,seed,refresh){
 const dialog=document.createElement('dialog');dialog.className='coverage-dialog';dialog.innerHTML='<form method="dialog"><h2>Adicionar cobertura</h2><p>Cada cobertura corresponde a um posto em uma data.</p><label>Dia do plantão<input name="date" type="date" required></label><label>Posto e horário<select name="slot"></select></label><p id="coverage-original"></p><label>Quem vai cobrir<select name="doctor" required></select></label><p>Registrar não altera a escala. Confirme depois que combinar com o médico.</p><div class="actions"><button type="submit">Registrar cobertura</button><button type="button" id="coverage-cancel" class="secondary">Cancelar</button></div></form>';root.append(dialog);
 const form=dialog.querySelector('form');let task=null;
 slots.forEach((label,i)=>{const [a,b]=bounds(i);form.elements.slot.add(new Option(`${label} · ${hour(a)}–${hour(b)} · ${b-a}h`,i));});
 function original(){const date=form.elements.date.value;dialog.querySelector('#coverage-original').textContent=date?'Previsto: '+(baseDoctor(seed,storage,date,Number(form.elements.slot.value))||'Vago').replaceAll('\n',' · '):'Escolha a data.';}
 form.elements.date.onchange=original;form.elements.slot.onchange=original;
 dialog.querySelector('#coverage-cancel').onclick=()=>dialog.close();
 const list=()=>parse(storage,'coverages',[]);
 const write=value=>{storage.setItem('rt-upa:coverages',JSON.stringify(value));const tasks=parse(storage,'organizer',[]);for(const item of tasks){if(item.kind!=='task'||item.status==='Resolvido')continue;const count=value.filter(x=>x.taskId===item.id&&x.confirmed).length;if(count>=(item.needed||1)&&['Precisa de cobertura','Aguardando confirmação'].includes(item.status))item.status='Em acompanhamento';else if(count<(item.needed||1)&&item.status==='Em acompanhamento'&&value.some(x=>x.taskId===item.id))item.status='Precisa de cobertura';}storage.setItem('rt-upa:organizer',JSON.stringify(tasks));refresh();document.dispatchEvent(new Event('rt-schedule-changed'));};
 form.onsubmit=e=>{e.preventDefault();const date=form.elements.date.value,slot=Number(form.elements.slot.value),[start,end]=bounds(slot);const item={id:crypto.randomUUID(),taskId:task.id,date,slot,start,end,doctor:form.elements.doctor.value,original:baseDoctor(seed,storage,date,slot),confirmed:false};try{validateCoverage(item,list());write([...list(),item]);dialog.close();}catch(error){alert(error.message);}};
 function open(item){task=item;form.reset();form.elements.date.value=item.date||'';const select=form.elements.doctor;select.replaceChildren(new Option('Selecione o médico',''));for(const d of [...new Set([...seed.physicians,...parse(storage,'doctors',[]),...parse(storage,'roster',[]).map(x=>x.doctor).filter(Boolean)])].sort())select.add(new Option(d.replaceAll('\n',' · '),d));original();dialog.showModal();}
 return function append(item,article,actions){if(item.kind!=='task')return;const rows=list().filter(x=>x.taskId===item.id),confirmed=rows.filter(x=>x.confirmed).length;const heading=document.createElement('p');heading.className='coverage-count';heading.textContent=`${item.type||'Pendência'} · ${confirmed}/${item.needed||1} coberturas confirmadas`;article.insertBefore(heading,actions);
 for(const c of rows){const line=document.createElement('div');line.className='coverage-line';const description=document.createElement('p');description.textContent=`${c.date.split('-').reverse().join('/')} · ${slots[c.slot]} · ${hour(c.start)}–${hour(c.end)}\n${(c.original||'Vago').replaceAll('\n',' · ')} → ${c.doctor.replaceAll('\n',' · ')}\n${c.confirmed?'Confirmada · já aparece na escala':'Aguardando confirmação'}`;line.append(description);const button=document.createElement('button');button.className='secondary';button.textContent=c.confirmed?'Desfazer cobertura':'Confirmar na escala';button.onclick=()=>{try{if(!c.confirmed){validateCoverage(c,list());if(baseDoctor(seed,storage,c.date,c.slot)!==c.original)throw new Error('O médico previsto mudou desde o registro. Remova esta cobertura e registre novamente para conferir os dados atuais.');}write(list().map(x=>x.id===c.id?{...x,confirmed:!c.confirmed}:x));}catch(error){alert(error.message);}};line.append(button);if(!c.confirmed){const remove=document.createElement('button');remove.className='secondary';remove.textContent='Remover rascunho';remove.onclick=()=>write(list().filter(x=>x.id!==c.id));line.append(remove);}article.insertBefore(line,actions);}
 const add=document.createElement('button');add.className='secondary';add.textContent='+ Adicionar cobertura';add.onclick=()=>open(item);actions.append(add);
 };
}
