export function dateKey(date = new Date()) {
  return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;
}
export function urgency(item, today = dateKey()) {
  if (item.status === 'Resolvido') return 'Resolvido';
  const due = item.reminder || item.date;
  if (!due) return 'Sem data';
  if (due < today) return 'Atrasado';
  if (due === today) return 'Hoje';
  const end = new Date(`${today}T12:00:00`); end.setDate(end.getDate()+7);
  return due <= dateKey(end) ? 'Próximos 7 dias' : 'Mais adiante';
}
export function mountOrganizer(storage) {
  const main = document.querySelector('main');
  const schedule = document.createElement('section'); schedule.id = 'schedule-panel';
  for (const child of [...main.children]) if (!child.classList.contains('account-bar')) schedule.append(child);
  main.append(schedule);
  const root = document.createElement('section'); root.id = 'organizer';
  root.innerHTML = `<nav class="workspace-nav" aria-label="Áreas do sistema"><button data-view="overview">Resumo</button><button data-view="schedule">Escala</button><button data-view="tasks">Pendências</button><button data-view="notes">Anotações</button></nav>
  <section id="overview-panel"><div class="welcome"><div><p class="eyebrow">SEU ESPAÇO DE ORGANIZAÇÃO</p><h2>Um dia de cada vez.</h2><p>Escala, coberturas e lembretes reunidos em um só lugar.</p></div><button data-new="task">+ Nova pendência</button></div><div id="metrics" class="metrics"></div><div class="section-heading"><h2>O que precisa da sua atenção</h2><span>Hoje e próximos sete dias</span></div><div id="upcoming" class="entry-list"></div></section>
  <section id="tasks-panel" hidden><div class="section-heading"><div><h2>Pendências e lembretes</h2><p>Acompanhe cada cobertura até a confirmação final.</p></div><button data-new="task">+ Nova pendência</button></div><label>Mostrar<select id="task-filter"><option value="open">Em aberto</option><option value="all">Todas</option><option value="resolved">Resolvidas</option></select></label><div id="task-list" class="entry-list"></div></section>
  <section id="notes-panel" hidden><div class="section-heading"><div><h2>Meu caderno da RT</h2><p>Observações e assuntos para acompanhar.</p></div><button data-new="note">+ Nova anotação</button></div><div id="note-list" class="entry-list"></div></section>
  <section id="editor-panel" class="card" hidden><h2 id="editor-title"></h2><form id="organizer-form"><label>Título<input name="title" required maxlength="160" placeholder="Ex.: confirmar cobertura de plantão"></label><div class="task-fields form-grid"><label>Dia do plantão<input name="date" type="date"></label><label>Lembrar em<input name="reminder" type="date"></label><label>Turno<select name="shift"><option value="">Não definido</option><option>Diurno</option><option>Noturno</option><option>Visitador</option></select></label><label>Situação<select name="status"><option>Precisa de cobertura</option><option>Aguardando confirmação</option><option>Em acompanhamento</option><option>Resolvido</option></select></label><label>Médico(a) envolvido(a)<input name="doctor" maxlength="500"></label><label>Quem vai cobrir<input name="cover" maxlength="500"></label></div><label>Anotações<textarea name="body" rows="5" maxlength="10000" placeholder="Combine os detalhes e registre o próximo passo."></textarea></label><p class="notice">Os lembretes aparecem aqui no sistema. Após registrar, clique em Salvar online.</p><div class="actions"><button>Registrar</button><button type="button" class="secondary" id="cancel-editor">Cancelar</button></div></form></section>`;
  main.insertBefore(root, schedule);
  const period = document.createElement('section'); period.className = 'period-reminders'; schedule.prepend(period);
  let view = 'overview', editing = null, kind = 'task';
  const read = () => { try { const data=JSON.parse(storage.getItem('rt-upa:organizer')); return Array.isArray(data)?data:[]; } catch { return []; } };
  const write = items => { storage.setItem('rt-upa:organizer',JSON.stringify(items)); render(); };
  const fmt = value => value ? new Date(`${value}T12:00:00`).toLocaleDateString('pt-BR') : '';
  function navigate(next) { view=next; for(const name of ['overview','tasks','notes']) root.querySelector(`#${name}-panel`).hidden=name!==view; schedule.hidden=view!=='schedule'; root.querySelector('#editor-panel').hidden=true; for(const button of root.querySelectorAll('[data-view]')) { button.classList.toggle('active',button.dataset.view===view); button.setAttribute('aria-current',button.dataset.view===view?'page':'false'); } }
  function editor(item, type='task') { editing=item?.id || null; kind=item?.kind || type; const form=root.querySelector('form'); form.reset(); for(const field of ['title','date','reminder','shift','status','doctor','cover','body']) if(item?.[field]!==undefined) form.elements[field].value=item[field]; root.querySelector('.task-fields').hidden=kind==='note'; root.querySelector('#editor-title').textContent=(editing?'Editar':'Nova')+(kind==='note'?' anotação':' pendência'); root.querySelector('#editor-panel').hidden=false; root.querySelector('#editor-panel').scrollIntoView({behavior:'smooth',block:'start'}); form.elements.title.focus(); }
  function card(item) { const article=document.createElement('article'); article.className='organizer-card'; const tag=document.createElement('span'); tag.className='tag'; tag.textContent=item.kind==='note'?'Anotação':`${urgency(item)} · ${item.status}`; if(['Hoje','Atrasado'].includes(urgency(item))) tag.classList.add('urgent'); const title=document.createElement('h3'); title.textContent=item.title; const detail=document.createElement('p'); detail.className='muted'; detail.textContent=[item.date&&`Plantão: ${fmt(item.date)}`,item.shift,item.reminder&&`Lembrar: ${fmt(item.reminder)}`,item.doctor&&`Médico(a): ${item.doctor}`,item.cover&&`Cobertura: ${item.cover}`].filter(Boolean).join(' · '); const body=document.createElement('p'); body.className='note-body'; body.textContent=item.body; const actions=document.createElement('div'); actions.className='actions'; const edit=document.createElement('button'); edit.className='secondary'; edit.textContent='Editar'; edit.onclick=()=>editor(item); actions.append(edit); if(item.kind==='task'){const done=document.createElement('button'); done.className='secondary'; done.textContent=item.status==='Resolvido'?'Reabrir':'Marcar resolvido'; done.onclick=()=>write(read().map(x=>x.id===item.id?{...x,status:item.status==='Resolvido'?'Em acompanhamento':'Resolvido'}:x)); actions.append(done); if(item.date){const open=document.createElement('button');open.className='secondary';open.textContent='Ver na escala';open.onclick=()=>{const [y,m,d]=item.date.split('-');document.querySelector('#year').value=y;document.querySelector('#month').value=Number(m);document.querySelector('#half').value=Number(d)<=15?'1':'2';document.querySelector('#generate').click();navigate('schedule');};actions.append(open);}} article.append(tag,title,detail,body,actions); return article; }
  function list(target,items,empty) { target.replaceChildren(); if(!items.length){const p=document.createElement('p');p.className='empty-state';p.textContent=empty;target.append(p);} else items.forEach(item=>target.append(card(item))); }
  function render(){const items=read(),tasks=items.filter(x=>x.kind==='task').sort((a,b)=>(a.reminder||a.date||'9999').localeCompare(b.reminder||b.date||'9999')); const active=tasks.filter(x=>x.status!=='Resolvido'); const metrics=root.querySelector('#metrics'); metrics.replaceChildren(); for(const [label,count] of [['Em aberto',active.length],['Atrasadas',active.filter(x=>urgency(x)==='Atrasado').length],['Hoje',active.filter(x=>urgency(x)==='Hoje').length],['Próximos 7 dias',active.filter(x=>urgency(x)==='Próximos 7 dias').length]]){const c=document.createElement('div');c.className='metric';const n=document.createElement('strong');n.textContent=count;const t=document.createElement('span');t.textContent=label;c.append(n,t);metrics.append(c);} list(root.querySelector('#upcoming'),active.filter(x=>['Atrasado','Hoje','Próximos 7 dias'].includes(urgency(x))),'Tudo em dia por aqui. Cadastre uma pendência para acompanhar os próximos passos.'); const filter=root.querySelector('#task-filter').value;list(root.querySelector('#task-list'),tasks.filter(x=>filter==='all'||(filter==='resolved'?x.status==='Resolvido':x.status!=='Resolvido')),'Nenhuma pendência nesta seleção.');list(root.querySelector('#note-list'),items.filter(x=>x.kind==='note'),'Seu caderno está pronto. Adicione sua primeira anotação.');renderPeriod(); }
  function renderPeriod(){const y=Number(document.querySelector('#year').value),m=Number(document.querySelector('#month').value),half=Number(document.querySelector('#half').value);const items=read().filter(x=>x.kind==='task'&&x.status!=='Resolvido'&&x.date).filter(x=>{const [iy,im,id]=x.date.split('-').map(Number);return iy===y&&im===m&&(half===1?id<=15:id>15);});period.hidden=!items.length;list(period,items,'');}
  root.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>navigate(b.dataset.view));root.querySelectorAll('[data-new]').forEach(b=>b.onclick=()=>editor(null,b.dataset.new));root.querySelector('#task-filter').onchange=render;root.querySelector('#cancel-editor').onclick=()=>root.querySelector('#editor-panel').hidden=true;
  root.querySelector('form').onsubmit=e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));data.title=data.title.trim();if(!data.title)return;const item={...data,id:editing||crypto.randomUUID(),kind};const items=read();write(editing?items.map(x=>x.id===editing?item:x):[item,...items]);navigate(kind==='note'?'notes':'tasks');};
  document.querySelector('#generate').addEventListener('click',renderPeriod); document.addEventListener('rt-data-restored',render);render();navigate('overview');
}
