import {parse,doctorIdentity,doctorChoices} from './scheduling.js';
import {coverageUI} from './coverage-ui.js';
export function dateKey(date = new Date()) {
  return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;
}
export function urgency(item, today = dateKey()) {
  if (item.status === 'Resolvido') return 'Resolvido';
  const due = item.reminder || item.date;
  if (!due) return 'Sem data';
  if (due < today) return 'Atrasado';
  if (due === today) return 'Hoje';
  const end = new Date(`${today}T12:00:00`); end.setDate(end.getDate()+7);
  return due <= dateKey(end) ? 'Próximos 7 dias' : 'Mais adiante';
}
export function mountOrganizer(storage,seed) {
  const main = document.querySelector('main');
  const schedule = document.createElement('section'); schedule.id = 'schedule-panel';
  for (const child of [...main.children]) if (!child.classList.contains('account-bar')) schedule.append(child);
  main.append(schedule);
  const root = document.createElement('section'); root.id = 'organizer';
  root.innerHTML = `<nav class="workspace-nav" aria-label="Áreas do sistema"><button data-view="overview">Painel</button><button data-view="flow">Fluxo de pacientes</button><button data-view="production">Produção médica</button><button data-view="schedule">Escala</button><button data-view="assistant">Assistente</button><button data-view="roster">Médicos e fixos</button><button data-view="lotacao">Lotação</button><button data-view="documentos">Documentos</button><button data-view="tasks">Pendências</button><button data-view="notes">Anotações</button></nav>
  <section id="overview-panel"><div class="welcome painel-hero"><div><p class="eyebrow">PAINEL DA UPA · PASCOAL RAMOS</p><h2 class="painel-saudacao">Olá</h2><p class="painel-data"></p><p class="painel-turno"></p></div><button data-new="task">+ Nova pendência</button></div><div data-slot="fluxo"></div><div data-slot="resumo"></div><div data-slot="atencao"></div><div data-slot="alertas"></div><div class="painel-duas"><section class="painel-bloco"><div class="section-heading"><div><h2>Pendências</h2><p>Atrasadas, de hoje e dos próximos sete dias</p></div></div><div id="metrics" class="metrics" hidden></div><div id="upcoming" class="entry-list"></div></section><div data-slot="hoje" class="painel-bloco"></div></div><div data-slot="busca"></div><div data-slot="extra"></div></section>
  <section id="flow-panel" class="flow" hidden></section><section id="production-panel" class="flow production" hidden></section><section id="assistant-panel" hidden></section><section id="roster-panel" hidden></section><section id="lotacao-panel" class="lotacao" hidden></section><section id="documentos-panel" class="documentos" hidden></section><section id="tasks-panel" hidden><div class="section-heading"><div><h2>Pendências e lembretes</h2><p>Acompanhe cada cobertura até a confirmação final.</p></div><button data-new="task">+ Nova pendência</button></div><label>Mostrar<select id="task-filter"><option value="open">Em aberto</option><option value="all">Todas</option><option value="resolved">Resolvidas</option></select></label><div id="task-list" class="entry-list"></div></section>
  <section id="notes-panel" hidden><div class="section-heading"><div><h2>Meu caderno da RT</h2><p>Observações e assuntos para acompanhar.</p></div><button data-new="note">+ Nova anotação</button></div><div id="note-list" class="entry-list"></div></section>
  <section id="editor-panel" class="card" hidden><h2 id="editor-title"></h2><form id="organizer-form"><label>Título<input name="title" required maxlength="160" placeholder="Ex.: confirmar cobertura de plantão"></label><div class="task-fields form-grid"><label>Tipo de pendência<select name="type"><option>Cobertura</option><option>Troca de plantão</option><option>Atestado / afastamento</option><option>Férias</option><option>Outro</option></select></label><label>Coberturas necessárias<input name="needed" type="number" min="1" max="20" value="1"></label><label>Dia do plantão<input name="date" type="date"></label><label id="vacation-end" hidden>Fim das férias<input name="endDate" type="date"></label><label>Lembrar em<input name="reminder" type="date"></label><label>Turno<select name="shift"><option value="">Não definido</option><option>Diurno</option><option>Noturno</option><option>Visitador</option><option>Cinderela</option></select></label><label>Situação<select name="status"><option>Precisa de cobertura</option><option>Aguardando confirmação</option><option>Em acompanhamento</option><option>Resolvido</option></select></label><label>Médico(a) envolvido(a)<input name="doctor" maxlength="500" autocomplete="off"></label><label>Observação sobre cobertura (opcional)<input name="cover" maxlength="500"></label></div><label>Anotações<textarea name="body" rows="5" maxlength="10000" placeholder="Combine os detalhes e registre o próximo passo."></textarea></label><p class="notice">Após registrar, use Adicionar cobertura para vincular cada médico ao posto. As alterações são salvas automaticamente online. Férias geram aviso durante todo o período, mesmo com a pendência resolvida. Para cancelar férias, edite o tipo para Outro.</p><div class="actions"><button>Registrar</button><button type="button" class="secondary" id="cancel-editor">Cancelar</button></div></form></section>`;
  // A barra de abas (nav) fica sozinha, fora de #organizer: se ficasse dentro, quando a Escala
  // estivesse aberta #organizer encolhia pra quase a altura da própria barra (o resto do conteúdo
  // mora em #schedule-panel, ao lado), e "position: sticky" não tinha espaço nenhum pra grudar no
  // topo ao rolar — a barra sumia da tela junto com o resto.
  const nav = root.querySelector('.workspace-nav');
  main.insertBefore(root, schedule);
  main.insertBefore(nav, root);
  const period = document.createElement('section'); period.className = 'period-reminders'; schedule.prepend(period);
  let view = 'overview', editing = null, kind = 'task';
  const read = () => { try { const data=JSON.parse(storage.getItem('rt-upa:organizer')); return Array.isArray(data)?data:[]; } catch { return []; } };
  const write = items => { storage.setItem('rt-upa:organizer',JSON.stringify(items)); render(); document.dispatchEvent(new Event('rt-schedule-changed')); };
  const fmt = value => value ? new Date(`${value}T12:00:00`).toLocaleDateString('pt-BR') : '';
  function navigate(next) { view=next; for(const name of ['overview','flow','production','tasks','notes','roster','lotacao','documentos','assistant']) root.querySelector(`#${name}-panel`).hidden=name!==view; schedule.hidden=view!=='schedule'; root.querySelector('#editor-panel').hidden=true; for(const button of nav.querySelectorAll('[data-view]')) { button.classList.toggle('active',button.dataset.view===view); button.setAttribute('aria-current',button.dataset.view===view?'page':'false'); } }
  function editor(item, type='task') { editing=item?.id || null; kind=item?.kind || type; const form=root.querySelector('#organizer-form'); form.reset(); for(const field of ['title','date','reminder','shift','status','doctor','cover','body','type','needed','endDate']) if(item?.[field]!==undefined) form.elements[field].value=field==='doctor'?item[field].replaceAll('\n',' · '):item[field]; root.querySelector('.task-fields').hidden=kind==='note'; root.querySelector('#editor-title').textContent=(editing?'Editar':'Nova')+(kind==='note'?' anotação':' pendência'); root.querySelector('#editor-panel').hidden=false; root.querySelector('#editor-panel').scrollIntoView({behavior:'smooth',block:'start'}); doctorInput.setCustomValidity('');taskForm.elements.endDate.setCustomValidity('');configureVacation();form.elements.title.focus(); }
  function card(item) { const article=document.createElement('article'); article.className='organizer-card'; const tag=document.createElement('span'); tag.className='tag'; tag.textContent=item.kind==='note'?'Anotação':`${urgency(item)} · ${item.status}`; if(['Hoje','Atrasado'].includes(urgency(item))) tag.classList.add('urgent'); const title=document.createElement('h3'); title.textContent=item.title; const detail=document.createElement('p'); detail.className='muted'; detail.textContent=[item.type==='Férias'?`Férias: ${fmt(item.date)} a ${fmt(item.endDate)}`:item.date&&`Plantão: ${fmt(item.date)}`,item.shift,item.reminder&&`Lembrar: ${fmt(item.reminder)}`,item.doctor&&`Médico(a): ${item.doctor}`,item.cover&&`Cobertura: ${item.cover}`].filter(Boolean).join(' · '); const body=document.createElement('p'); body.className='note-body'; body.textContent=item.body; const actions=document.createElement('div'); actions.className='actions'; const edit=document.createElement('button'); edit.className='secondary'; edit.textContent='Editar'; edit.onclick=()=>editor(item); actions.append(edit); if(item.kind==='task'){const done=document.createElement('button'); done.className='secondary'; done.textContent=item.status==='Resolvido'?'Reabrir':'Marcar resolvido'; done.onclick=()=>write(read().map(x=>x.id===item.id?{...x,status:item.status==='Resolvido'?'Em acompanhamento':'Resolvido'}:x)); actions.append(done); if(item.date){const open=document.createElement('button');open.className='secondary';open.textContent='Ver na escala';open.onclick=()=>{const [y,m,d]=item.date.split('-');document.querySelector('#year').value=y;document.querySelector('#month').value=Number(m);document.querySelector('#half').value=Number(d)<=15?'1':'2';document.querySelector('#generate').click();document.dispatchEvent(new CustomEvent('rt-open-date',{detail:item.date}));navigate('schedule');};actions.append(open);}} article.append(tag,title,detail,body,actions);appendCoverages(item,article,actions); return article; }
  function list(target,items,empty) { target.replaceChildren(); if(!items.length){const p=document.createElement('p');p.className='empty-state';p.textContent=empty;target.append(p);} else items.forEach(item=>target.append(card(item))); }
  function render(){const items=read(),tasks=items.filter(x=>x.kind==='task').sort((a,b)=>(a.reminder||a.date||'9999').localeCompare(b.reminder||b.date||'9999')); const active=tasks.filter(x=>x.status!=='Resolvido'); const metrics=root.querySelector('#metrics'); metrics.replaceChildren(); for(const [label,count] of [['Em aberto',active.length],['Atrasadas',active.filter(x=>urgency(x)==='Atrasado').length],['Hoje',active.filter(x=>urgency(x)==='Hoje').length],['Próximos 7 dias',active.filter(x=>urgency(x)==='Próximos 7 dias').length]]){const c=document.createElement('div');c.className='metric';const n=document.createElement('strong');n.textContent=count;const t=document.createElement('span');t.textContent=label;c.append(n,t);metrics.append(c);} list(root.querySelector('#upcoming'),active.filter(x=>['Atrasado','Hoje','Próximos 7 dias'].includes(urgency(x))),'Tudo em dia por aqui. Cadastre uma pendência para acompanhar os próximos passos.'); const filter=root.querySelector('#task-filter').value;list(root.querySelector('#task-list'),tasks.filter(x=>filter==='all'||(filter==='resolved'?x.status==='Resolvido':x.status!=='Resolvido')),'Nenhuma pendência nesta seleção.');list(root.querySelector('#note-list'),items.filter(x=>x.kind==='note'),'Seu caderno está pronto. Adicione sua primeira anotação.');renderPeriod(); }
  function renderPeriod(){const y=Number(document.querySelector('#year').value),m=Number(document.querySelector('#month').value),half=Number(document.querySelector('#half').value);const items=read().filter(x=>x.kind==='task'&&x.status!=='Resolvido'&&x.date).filter(x=>{const [iy,im,id]=x.date.split('-').map(Number);return iy===y&&im===m&&(half===1?id<=15:id>15);});period.hidden=!items.length;list(period,items,'');}
  nav.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>navigate(b.dataset.view));root.querySelectorAll('[data-new]').forEach(b=>b.onclick=()=>editor(null,b.dataset.new));root.querySelector('#task-filter').onchange=render;root.querySelector('#cancel-editor').onclick=()=>root.querySelector('#editor-panel').hidden=true;
  const taskForm=root.querySelector('#organizer-form'),doctorInput=taskForm.elements.doctor;
  const suggestions=document.createElement('div');suggestions.className='doctor-suggestions';suggestions.setAttribute('aria-label','Sugestões de médicos');doctorInput.after(suggestions);
  const allDoctors=()=>doctorChoices(seed,storage);
  const displayDoctor=d=>d.replaceAll('\n',' · ');
  function suggest(){suggestions.replaceChildren();const query=doctorIdentity(doctorInput.value);if(query.length<2)return;for(const doctor of allDoctors().filter(d=>doctorIdentity(d).includes(query)).slice(0,10)){const b=document.createElement('button');b.type='button';b.className='secondary';b.textContent=displayDoctor(doctor);b.onclick=()=>{doctorInput.setCustomValidity('');doctorInput.value=displayDoctor(doctor);suggestions.replaceChildren();};suggestions.append(b);}}
  doctorInput.addEventListener('input',()=>{doctorInput.setCustomValidity('');suggest();});
  function configureVacation(){const active=kind==='task'&&taskForm.elements.type.value==='Férias';root.querySelector('#vacation-end').hidden=!active;taskForm.elements.endDate.required=active;taskForm.elements.date.required=active;doctorInput.required=active;taskForm.elements.date.parentElement.firstChild.textContent=active?'Início das férias':'Dia do plantão';suggestions.replaceChildren();}
  taskForm.elements.type.onchange=configureVacation;
  root.querySelector('#organizer-form').onsubmit=e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));data.title=data.title.trim();if(!data.title)return;if(data.type==='Férias'&&kind==='task'){if(!data.date||!data.endDate||data.endDate<data.date){taskForm.elements.endDate.setCustomValidity('Escolha uma data final igual ou posterior ao início.');taskForm.elements.endDate.reportValidity();return;}const match=allDoctors().find(d=>displayDoctor(d)===data.doctor||d===data.doctor);if(!match){doctorInput.setCustomValidity('Selecione o médico nas sugestões para vincular as férias à escala.');doctorInput.reportValidity();return;}data.doctor=match;}else data.endDate='';data.needed=Number(data.needed||1);const item={...data,id:editing||crypto.randomUUID(),kind};const items=read();write(editing?items.map(x=>x.id===editing?item:x):[item,...items]);navigate(kind==='note'?'notes':'tasks');};
  taskForm.elements.endDate.oninput=()=>taskForm.elements.endDate.setCustomValidity('');
  const appendCoverages=coverageUI(root,storage,seed,render);
  document.querySelector('#generate').addEventListener('click',renderPeriod); document.addEventListener('rt-data-restored',render);render();navigate('overview');
}
