import {slots,bounds,hour,parse,doctorIdentity,affiliation,affiliationClass,recurringRule,patternFor} from './scheduling.js';
const slotLabel=i=>`${slots[i]} · ${hour(bounds(i)[0])}–${hour(bounds(i)[1])}`;
const days=['Domingo','Segunda','Terça','Quarta','Quinta','Sexta','Sábado'];
const fmt=value=>value.split('-').reverse().join('/');
export function mountRoster(storage,seed){
 const root=document.querySelector('#roster-panel');
 root.innerHTML=`<div class="section-heading"><div><p class="eyebrow">PADRÃO PARA AS PRÓXIMAS ESCALAS</p><h2>Médicos e dias fixos</h2></div><button id="roster-add">+ Novo dia fixo</button></div><p>Consulte por data. Mudanças valem a partir do dia informado e mantêm o histórico anterior. A escala usa os padrões automaticamente em períodos novos; ajustes pontuais e coberturas confirmadas têm prioridade.</p><div class="form-grid"><label>Válidos em<input id="roster-date" type="date" required></label><label>Buscar médico<input id="roster-search" type="search" placeholder="Digite parte do nome"></label></div><p id="roster-source" class="notice"></p><p class="link-legend"><span class="affiliation link-sms">SMS · fixo</span> <span class="affiliation link-coaph">COAPH</span> <span class="affiliation link-extra">Extra SMS · não repetido automaticamente</span></p><div id="roster-cards" class="day-cards"></div><details><summary id="roster-review-title">Postos para revisar</summary><div id="roster-review"></div></details><details><summary>Histórico das alterações de padrão</summary><div id="roster-history"></div></details><dialog class="coverage-dialog" id="roster-dialog"><form><h2 id="roster-edit-title">Dia fixo</h2><label>Médico<select name="doctor" required></select></label><div class="form-grid"><label>Vínculo neste plantão<select name="affiliation"><option>SMS</option><option>COAPH</option><option>EXTRA SMS</option></select></label><label>Dia da semana<select name="weekday"></select></label><label>Posto e horário<select name="slot"></select></label><label>Válido a partir de<input name="start" type="date" required></label></div><label><input type="checkbox" name="end"> Encerrar este dia fixo a partir da data informada</label><p id="roster-impact" role="status"></p><label id="roster-replace-label" hidden><input type="checkbox" name="replace"> Confirmo substituir o médico que ocupa esse posto no padrão</label><p class="notice">O vínculo pertence a este plantão. Alterar aqui não muda outros vínculos do mesmo médico. Extras exigem ajuste por data e não serão repetidos como fixos.</p><div class="actions"><button type="submit">Salvar mudança</button><button type="button" class="secondary" id="roster-cancel">Cancelar</button></div></form></dialog>`;
 const date=root.querySelector('#roster-date');date.value=document.querySelector('#schedule-date').value;
 const form=root.querySelector('form'),dialog=root.querySelector('dialog');let original=null;
 const people=()=>{const map=new Map();for(const d of [...seed.physicians,...parse(storage,'doctors',[]),...parse(storage,'roster',[]).map(x=>x.doctor).filter(Boolean)])if(!map.has(doctorIdentity(d)))map.set(doctorIdentity(d),d);return [...map.values()].sort((a,b)=>a.localeCompare(b,'pt-BR'));};
 const name=d=>d.split(/CRM/i)[0].trim();
 const changeDoctor=(d,link)=>`${name(d)}\nCRM ${d.match(/CRM\s*(\d+)/i)?.[1]||''} - ${link}`;
 days.forEach((d,i)=>form.elements.weekday.add(new Option(d,i)));slots.forEach((s,i)=>form.elements.slot.add(new Option(slotLabel(i)+` · ${bounds(i)[1]-bounds(i)[0]}h`,i)));
 function impact(){const start=form.elements.start.value,slot=Number(form.elements.slot.value),weekday=Number(form.elements.weekday.value);if(!start)return false;const target=recurringRule(seed,storage,start,weekday,slot);const replacing=!!target?.doctor&&doctorIdentity(target.doctor)!==doctorIdentity(form.elements.doctor.value)&&!form.elements.end.checked;root.querySelector('#roster-replace-label').hidden=!replacing;const moves=original&&(original.weekday!==weekday||original.slot!==slot);root.querySelector('#roster-impact').textContent=form.elements.end.checked?`O posto ficará sem médico fixo a partir de ${fmt(start)}. Dias anteriores permanecem iguais.`:`${days[weekday]} · ${slots[slot]}, a partir de ${fmt(start)}.${moves?' O dia/posto anterior será liberado a partir dessa data.':''}${replacing?' Neste posto está '+name(target.doctor)+'.':''}`;return replacing;}
 function open(rule,doctor=''){original=rule?{...rule}:null;form.reset();form.elements.doctor.replaceChildren(new Option('Selecione o médico',''));for(const d of people())form.elements.doctor.add(new Option(name(d),d));const selected=doctor||rule?.doctor||'';const match=people().find(d=>doctorIdentity(d)===doctorIdentity(selected));form.elements.doctor.value=match||'';form.elements.affiliation.value=affiliation(selected)||'SMS';form.elements.weekday.value=rule?.weekday??1;form.elements.slot.value=rule?.slot??0;form.elements.start.value=date.value;root.querySelector('#roster-edit-title').textContent=rule?'Alterar dia fixo':'Novo dia fixo';impact();dialog.showModal();}
 form.onchange=e=>{if(e.target!==form.elements.replace)form.elements.replace.checked=false;impact();};root.querySelector('#roster-cancel').onclick=()=>dialog.close();root.querySelector('#roster-add').onclick=()=>open();
 form.onsubmit=e=>{e.preventDefault();if(affiliation(changeDoctor(form.elements.doctor.value,form.elements.affiliation.value))==='EXTRA SMS'&&!form.elements.end.checked){root.querySelector('#roster-impact').textContent='Extra SMS é pontual. Escolha o médico e vínculo extra no plantão da data específica, na aba Escala.';return;}if(impact()&&!form.elements.replace.checked)return;const start=form.elements.start.value,weekday=Number(form.elements.weekday.value),slot=Number(form.elements.slot.value),doctor=form.elements.end.checked?'':changeDoctor(form.elements.doctor.value,form.elements.affiliation.value);let rules=parse(storage,'roster',[]);const put=(w,s,d)=>{rules=rules.filter(x=>!(x.start===start&&x.weekday===w&&x.slot===s));rules.push({id:crypto.randomUUID(),start,weekday:w,slot:s,doctor:d});};if(original&&(original.weekday!==weekday||original.slot!==slot))put(original.weekday,original.slot,'');put(weekday,slot,doctor);storage.setItem('rt-upa:roster',JSON.stringify(rules));date.value=start;dialog.close();document.dispatchEvent(new Event('rt-schedule-changed'));};
 function render(){if(!date.value)return;const pattern=patternFor(seed,date.value);root.querySelector('#roster-source').textContent=pattern?`Base: ${pattern.source}. SMS repetidos foram organizados como fixos; COAPH repetidos como padrão habitual. Extras e posições variáveis precisam de revisão.`:'Sem padrão importado para este período. Você pode cadastrar dias fixos.';const conflicts=seed.assignments.filter(x=>x.date.slice(0,7)===date.value.slice(0,7)&&x.colorAffiliation&&x.colorAffiliation!==x.affiliation);if(conflicts.length)root.querySelector('#roster-source').textContent+=' Atenção: '+conflicts.map(x=>name(x.doctor)+' em '+fmt(x.date)).join('; ')+' têm divergência entre texto e cor. Mantido o vínculo escrito, sem assumir fixo.';const groups=new Map(),review=[];for(let w=0;w<7;w++)for(let slot=0;slot<16;slot++){const r=recurringRule(seed,storage,date.value,w,slot);if(!r)continue;const rule={...r,weekday:w,slot};if(r.doctor){const key=doctorIdentity(r.doctor);if(!groups.has(key))groups.set(key,{doctor:r.doctor,rules:[]});groups.get(key).rules.push(rule);}else if(r.status==='review')review.push(rule);}
 const cards=root.querySelector('#roster-cards');cards.replaceChildren();const query=doctorIdentity(root.querySelector('#roster-search').value);for(const group of [...groups.values()].sort((a,b)=>name(a.doctor).localeCompare(name(b.doctor),'pt-BR'))){if(query&&!doctorIdentity(group.doctor).includes(query))continue;const card=document.createElement('article');card.className='shift-card';const h=document.createElement('h3');h.textContent=name(group.doctor);card.append(h);for(const r of group.rules){const row=document.createElement('div');row.className='roster-line';const p=document.createElement('p');p.textContent=`${days[r.weekday]} · ${slotLabel(r.slot)}`;const badge=document.createElement('span');badge.className='affiliation '+affiliationClass(r.doctor);badge.textContent=affiliation(r.doctor);const button=document.createElement('button');button.className='secondary';button.textContent='Alterar';button.setAttribute('aria-label',`Alterar ${name(group.doctor)} ${days[r.weekday]} ${slotLabel(r.slot)}`);button.onclick=()=>open(r);row.append(p,badge,button);card.append(row);}const add=document.createElement('button');add.className='secondary';add.textContent='+ Outro dia fixo';add.onclick=()=>open(null,group.doctor);card.append(add);cards.append(card);}if(!cards.children.length)cards.textContent='Nenhum médico com dia fixo nesta seleção.';
 const target=root.querySelector('#roster-review');target.replaceChildren();root.querySelector('#roster-review-title').textContent=`Postos para revisar (${review.length})`;for(const r of review){const line=document.createElement('div');line.className='roster-line';const p=document.createElement('p');p.textContent=`${days[r.weekday]} · ${slotLabel(r.slot)} — ${r.candidates?.length?'Nomes encontrados: '+r.candidates.map(name).join(', '):'Só extras ou vagas na referência'}`;const b=document.createElement('button');b.textContent='Definir fixo';b.className='secondary';b.onclick=()=>open(r,r.candidates?.[0]);line.append(p,b);target.append(line);}
 const history=root.querySelector('#roster-history');history.replaceChildren();for(const r of parse(storage,'roster',[]).sort((a,b)=>b.start.localeCompare(a.start))){const p=document.createElement('p');p.textContent=`Desde ${fmt(r.start)} · ${days[r.weekday]} · ${slotLabel(r.slot)}: ${r.doctor.replaceAll('\n',' · ')||'Sem fixo'}`;history.append(p);}if(!history.children.length)history.textContent='Nenhuma alteração manual de padrão.';
 }
 date.onchange=render;root.querySelector('#roster-search').oninput=render;document.addEventListener('rt-schedule-changed',render);document.addEventListener('rt-data-restored',render);render();
}
