import {doctorPicker} from './doctor-picker.js';
import {registrarTroca} from './historico.js';
import {overlapIndex,overlapMessage,slots,bounds,hour,parse,baseDoctor,segments,periodKey,vacationConflicts,vacationMessage,affiliation,affiliationClass,patternFor,recurringRule,doctorIdentity,clinicoOccupancy,doctorChoices,doctorOptions,doctorLabel,withAffiliation,AFFILIATIONS} from './scheduling.js';
const days=['Domingo','Segunda','Terça','Quarta','Quinta','Sexta','Sábado'];
export function mountScheduleView(storage,seed){
 const host=document.querySelector('#schedule-panel'),view=document.createElement('section');view.className='daily-schedule';
 view.innerHTML='<div class="section-heading"><div><p class="eyebrow">ESCALA ATUAL</p><h2>Plantões do dia</h2></div><div class="actions"><button id="day-prev" class="secondary" aria-label="Dia anterior">←</button><label><span id="schedule-weekday">Data</span><input id="schedule-date" type="date"></label><button id="day-next" class="secondary" aria-label="Próximo dia">→</button><button id="day-today" class="secondary">Hoje</button></div></div><div class="schedule-tabs"><button data-group="day">Diurno · 12h</button><button data-group="night">Noturno · 12h</button><button data-group="cinderella">Cinderelas · 6h</button><button id="cinderela-excel" class="secondary">Excel Cinderelas · semana</button><button id="toggle-grid" class="secondary">Ver grade da quinzena</button><button id="copy-week" class="secondary">Copiar semana</button></div><p id="schedule-origin" class="notice"></p><div id="day-cards" class="day-cards"></div><p class="notice">Coberturas confirmadas nas pendências aparecem aqui e na exportação. O noturno termina às 7h do dia seguinte.</p><dialog class="coverage-dialog" id="copy-week-dialog"><form><h2>Copiar semana</h2><p class="notice">Escolha um dia de cada semana (domingo a sábado) — copiamos os 7 dias inteiros, todos os postos, substituindo o que já estiver definido no destino. Dias fixos e o padrão continuam valendo normalmente fora do período copiado.</p><label>Um dia qualquer da semana de origem<input name="source" type="date" required></label><label>Um dia qualquer da semana de destino<input name="target" type="date" required></label><p id="copy-week-preview" role="status"></p><div class="actions"><button type="submit">Copiar semana</button><button type="button" class="secondary" id="copy-week-cancel">Cancelar</button></div></form></dialog>';
 const summary=document.querySelector('#summary');summary.after(view);
 const grid=host.querySelector('section.card:has(#body)');grid.hidden=true;
 let group='day';const dateInput=view.querySelector('#schedule-date');const localDate=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;const dates=[...new Set(seed.assignments.filter(x=>x.slot<14).map(x=>x.date))].sort();const today=localDate(new Date());let remembered;try{remembered=sessionStorage.getItem('rt-view-date');}catch{}dateInput.value=/^\d{4}-\d{2}-\d{2}$/.test(remembered||'')?remembered:dates.includes(today)?today:(dates[0]||today);
 function render(){const date=dateInput.value;if(!date)return;const weekdayNames=['DOMINGO','SEGUNDA-FEIRA','TERÇA-FEIRA','QUARTA-FEIRA','QUINTA-FEIRA','SEXTA-FEIRA','SÁBADO'];view.querySelector('#schedule-weekday').textContent=`${weekdayNames[new Date(date+'T12:00:00').getDay()]} · ${date.split('-').reverse().join('/')}`;const overlaps=overlapIndex(seed,storage,[date]);try{sessionStorage.setItem('rt-view-date',date);}catch{}const container=view.querySelector('#day-cards');container.replaceChildren();for(const button of view.querySelectorAll('[data-group]'))button.classList.toggle('active',button.dataset.group===group);view.querySelector('#cinderela-excel').hidden=group!=='cinderella';const indices=group==='day'?[0,1,2,3,4,5,6]:group==='night'?[7,8,9,10,11,12,13]:[14,15];
 const imported=seed.assignments.some(x=>x.date===date&&x.slot<14),pattern=patternFor(seed,date);view.querySelector('#schedule-origin').textContent=group==='cinderella'?'Cinderelas · padrão semanal de 6 horas':imported?'Escala importada para esta data.':pattern?'Preenchida pelo padrão de dias fixos. Revise extras, vagas e afastamentos antes de fechar.':'Sem escala ou padrão para este período.';if(group!=='cinderella')container.append(clinicoAddCard(date));for(const slot of indices){const rule=recurringRule(seed,storage,date,new Date(date+'T12:00:00').getDay(),slot),exact=seed.assignments.find(x=>x.date===date&&x.slot===slot),edited=Object.hasOwn(parse(storage,periodKey(date),{}),`${date}|${slot}`);const known=rule?.status==='custom'||slot>=14||imported||!!pattern||Object.hasOwn(parse(storage,periodKey(date),{}),`${date}|${slot}`)||parse(storage,'fixed',[]).some(x=>Number(x.weekday)===new Date(date+'T12:00:00').getDay()&&Number(x.slot)===slot);const card=document.createElement('article');card.className='shift-card';const title=document.createElement('h3');title.textContent=slots[slot];const [a,b]=bounds(slot),time=document.createElement('p');time.className='shift-hours';time.textContent=`${hour(a)}–${hour(b)} · ${b-a} horas`;card.append(title,time);const current=segments(seed,storage,date,slot);for(const segment of current){
 // "Vago" precisa saltar aos olhos (é o que falta preencher pra fechar a escala) — os outros
 // estados de "sem médico" (sem previsão nesse dia, ainda sem escala carregada) ficam discretos,
 // senão tudo fica com a mesma cara de alerta e a atenção se perde.
 const emptyText=slot>=14&&[0,6].includes(new Date(date+'T12:00:00').getDay())?'Sem plantão fixo neste dia':!edited&&rule?.status!=='custom'&&exact?.availability==='not-scheduled'?'Não previsto na escala (X)':known?'Vago':'Sem escala carregada para esta data';
 const isVago=!segment.doctor&&emptyText==='Vago';
 const name=document.createElement('p');name.className='doctor-name '+(segment.doctor?affiliationClass(segment.doctor):(isVago?'slot-vago':'slot-unknown'));name.textContent=segment.doctor?segment.doctor.split('\n')[0]:emptyText;card.append(name);if(segment.doctor){const crm=document.createElement('small');crm.className='doctor-crm';crm.textContent=(segment.doctor.split('\n')[1]||'').split(' - ')[0];card.append(crm);}
 if(isVago)card.classList.add('needs-doctor');
if(segment.doctor){const badge=document.createElement('span');badge.className='affiliation '+affiliationClass(segment.doctor);badge.textContent=affiliation(segment.doctor);card.append(badge);}for(const leave of vacationConflicts(storage,segment.doctor,date,slot)){card.classList.add('vacation-conflict');const warning=document.createElement('p');warning.className='vacation-warning';warning.setAttribute('role','alert');warning.textContent=vacationMessage(leave);card.append(warning);}if(segment.coverage){card.classList.add('covered');const note=document.createElement('p');note.className='coverage-badge';note.textContent='Cobertura confirmada · previsto: '+(segment.original||'Vago').replaceAll('\n',' · ');card.append(note);}}
 if(exact?.doctor&&exact.colorAffiliation&&exact.colorAffiliation!==exact.affiliation){const warning=document.createElement('p');warning.className='notice';warning.textContent='Conferir vínculo: a planilha escreve '+exact.affiliation+', mas a cor indica '+exact.colorAffiliation+'. Mantido o texto original; não usado como fixo.';card.append(warning);}
 const collisions=overlaps.get(`${date}|${slot}`)||[];if(collisions.length){card.classList.add('overlap-conflict');for(const collision of collisions){const warning=document.createElement('p');warning.className='overlap-warning';warning.setAttribute('role','alert');warning.textContent=overlapMessage(collision);card.append(warning);}}
 const edit=document.createElement('details');edit.className='shift-edit';const temMedico=current.some(x=>x.doctor);edit.open=!temMedico||!known;const editTitle=document.createElement('summary');editTitle.textContent=temMedico?'Trocar médico':'Escolher médico';edit.append(editTitle);const label=document.createElement('label');label.textContent=known?'Ajustar médico previsto':'Definir médico para esta data';const select=document.createElement('select');select.setAttribute('aria-label',`${slots[slot]} em ${date}`);select.add(new Option(known?'— Vago —':'— Sem dados desta data —',''));const planned=baseDoctor(seed,storage,date,slot);for(const doctor of doctorOptions(doctorChoices(seed,storage),planned))select.add(new Option((vacationConflicts(storage,doctor,date,slot).length?'⚠ EM FÉRIAS · ':'')+doctorLabel(doctor),doctor));select.value=planned;select.disabled=current.some(x=>x.coverage);select.onchange=()=>{const key=periodKey(date),edits=parse(storage,key,{});registrarTroca(storage,{data:date,slot,saiu:planned,entrou:select.value});edits[`${date}|${slot}`]=select.value;storage.setItem('rt-upa:'+key,JSON.stringify(edits));document.dispatchEvent(new Event('rt-schedule-changed'));};label.append(select);edit.append(label);if(select.value){const linkLabel=document.createElement('label');linkLabel.textContent='Vínculo neste plantão';const link=document.createElement('select');link.className='link-select';link.setAttribute('aria-label',`Vínculo de ${slots[slot]} em ${date}`);for(const option of AFFILIATIONS)link.add(new Option(option,option));link.value=affiliation(select.value);link.disabled=select.disabled;link.onchange=()=>{const key=periodKey(date),edits=parse(storage,key,{});edits[`${date}|${slot}`]=withAffiliation(select.value,link.value);storage.setItem('rt-upa:'+key,JSON.stringify(edits));document.dispatchEvent(new Event('rt-schedule-changed'));};linkLabel.append(link);edit.append(linkLabel);}if(select.disabled){const small=document.createElement('p');small.className='notice';small.textContent='Para alterar, desfaça a cobertura na pendência.';edit.append(small);}
 const weekday=new Date(date+'T12:00:00').getDay();const alreadyFixedHere=rule?.status==='custom'&&rule.start<=date&&doctorIdentity(rule.doctor)===doctorIdentity(select.value)&&select.value;
 const fixButton=document.createElement('button');fixButton.type='button';fixButton.className='secondary';fixButton.textContent=alreadyFixedHere?'Já é fixo · alterar data de início':'Tornar fixo a partir desta data';fixButton.title='Repete este médico neste dia da semana e neste posto em todas as próximas quinzenas, até você mudar ou remover em Médicos e fixos.';
 fixButton.onclick=()=>{if(!select.value)return alert('Selecione um médico antes de tornar fixo.');if(!confirm(`Tornar ${select.value.split('\n')[0]} fixo toda ${days[weekday]} em ${slots[slot]}, a partir de ${date.split('-').reverse().join('/')}?`))return;let rules=parse(storage,'roster',[]).filter(x=>!(x.start===date&&x.weekday===weekday&&x.slot===slot));const regra={id:crypto.randomUUID(),start:date,weekday,slot,doctor:select.value};if(/EXTRA/i.test(select.value))regra.repeatExtra=true;rules.push(regra);storage.setItem('rt-upa:roster',JSON.stringify(rules));document.dispatchEvent(new Event('rt-schedule-changed'));};
 {const troca=parse(storage,'trocas',[]).find(t=>t.data===date&&t.slot===slot&&t.status!=='desfeita'&&doctorIdentity(t.entrou)===doctorIdentity(baseDoctor(seed,storage,date,slot)));if(troca){const aviso=document.createElement('p');aviso.className='troca-badge';aviso.textContent=`↺ Trocado pela produção · na escala estava ${troca.saiu.split('\n')[0]}`;card.append(aviso);}}
 // O botão "Tornar fixo" fica fora do bloco recolhível: assim aparece direto quando há médico no posto.
 if(select.value&&!select.disabled)card.append(fixButton);
 card.append(edit);
 container.append(card);doctorPicker(select);}}

 // Clínicos 1 a 4 são postos iguais: incluir um médico avulso usa a primeira posição livre,
 // sem precisar escolher o número (que só existe por causa da planilha oficial).
 function clinicoAddCard(date){
  const turn=group==='day'?'dia':'noite',occ=clinicoOccupancy(seed,storage,date,turn),card=document.createElement('article');card.className='shift-card clinico-add';
  const title=document.createElement('h3');title.textContent=`${group==='day'?'Diurno':'Noturno'} · Clínicos · ${occ.doctors.length}/${occ.total}`;card.append(title);
  if(!occ.free.length){const full=document.createElement('p');full.className='notice';full.textContent=`Completo: os ${occ.total} postos de clínico já têm médico. Para trocar alguém, ajuste o posto abaixo.`;card.append(full);return card;}
  const label=document.createElement('label');label.textContent=`Adicionar clínico · ${occ.free.length} ${occ.free.length===1?'vaga livre':'vagas livres'}`;
  const select=document.createElement('select');select.setAttribute('aria-label',`Adicionar clínico ${group==='day'?'diurno':'noturno'} em ${date}`);select.add(new Option('— Escolha o médico —',''));
  for(const doctor of doctorChoices(seed,storage))select.add(new Option((vacationConflicts(storage,doctor,date,occ.free[0]).length?'⚠ EM FÉRIAS · ':'')+doctorLabel(doctor),doctor));
  select.onchange=()=>{const doctor=select.value;if(!doctor)return;
   if(occ.doctors.some(x=>doctorIdentity(x)===doctorIdentity(doctor))&&!confirm(`${doctor.split('\n')[0]} já está como clínico neste turno. Incluir de novo?`)){select.value='';return;}
   const key=periodKey(date),edits=parse(storage,key,{});registrarTroca(storage,{data:date,slot:occ.free[0],saiu:'',entrou:doctor});edits[`${date}|${occ.free[0]}`]=doctor;storage.setItem('rt-upa:'+key,JSON.stringify(edits));document.dispatchEvent(new Event('rt-schedule-changed'));};
  label.append(select);card.append(label);queueMicrotask(()=>doctorPicker(select));return card;
 }
 view.querySelector('#cinderela-excel').onclick=async e=>{const b=e.currentTarget;b.disabled=true;try{const items={};for(let i=0;i<storage.length;i++){const key=storage.key(i);if(key.startsWith('rt-upa:'))items[key]=storage.getItem(key);}const response=await fetch('/api/export-cinderela',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({date:dateInput.value,items})});if(!response.ok)throw new Error('Não foi possível exportar. Confira seu acesso e tente novamente.');const blob=await response.blob(),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='ESCALA_CINDERELAS.xlsx';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}catch(err){alert(err.message);}finally{b.disabled=false;}};
 // "Copiar semana": duplica os 7 dias (domingo a sábado, todos os postos) de uma semana já
 // pronta pra outra semana futura — pra não ter que remontar tudo de novo quando a intenção
 // é repetir a mesma escala. Grava como ajustes de data (igual editar cada posto manualmente),
 // então dias fixos/padrão continuam normais fora do período copiado.
 const fmtBR=v=>v.split('-').reverse().join('/');
 const addWeekDays=(v,n)=>{const d=new Date(v+'T12:00:00');d.setDate(d.getDate()+n);return localDate(d);};
 const sundayOf=v=>addWeekDays(v,-(new Date(v+'T12:00:00').getDay()));
 const copyDialog=view.querySelector('#copy-week-dialog'),copyForm=copyDialog.querySelector('form');
 function copyPreview(){
  const src=copyForm.elements.source.value,tgt=copyForm.elements.target.value,p=view.querySelector('#copy-week-preview');
  if(!src||!tgt){p.textContent='';return;}
  const s0=sundayOf(src),t0=sundayOf(tgt);
  p.textContent=s0===t0?'Escolha uma semana de destino diferente da semana de origem.':`Semana de ${fmtBR(s0)} (dom) a ${fmtBR(addWeekDays(s0,6))} (sáb) será copiada para ${fmtBR(t0)} (dom) a ${fmtBR(addWeekDays(t0,6))} (sáb).`;
 }
 copyForm.elements.source.onchange=copyPreview;copyForm.elements.target.onchange=copyPreview;
 view.querySelector('#copy-week').onclick=()=>{copyForm.reset();copyForm.elements.source.value=dateInput.value;copyForm.elements.target.value='';view.querySelector('#copy-week-preview').textContent='';copyDialog.showModal();};
 view.querySelector('#copy-week-cancel').onclick=()=>copyDialog.close();
 copyForm.onsubmit=e=>{
  e.preventDefault();
  const src=copyForm.elements.source.value,tgt=copyForm.elements.target.value;
  if(!src||!tgt)return;
  const s0=sundayOf(src),t0=sundayOf(tgt);
  if(s0===t0)return;
  if(!confirm(`Copiar a semana de ${fmtBR(s0)} a ${fmtBR(addWeekDays(s0,6))} para ${fmtBR(t0)} a ${fmtBR(addWeekDays(t0,6))}? Isso substitui o que já estiver salvo nesses 7 dias no destino.`))return;
  for(let i=0;i<7;i++){
   const sourceDate=addWeekDays(s0,i),targetDate=addWeekDays(t0,i);
   if(sourceDate===targetDate)continue;
   const key=periodKey(targetDate),edits=parse(storage,key,{});
   for(let slot=0;slot<16;slot++)edits[`${targetDate}|${slot}`]=baseDoctor(seed,storage,sourceDate,slot);
   storage.setItem('rt-upa:'+key,JSON.stringify(edits));
  }
  copyDialog.close();
  dateInput.value=t0;syncDate();
  document.dispatchEvent(new Event('rt-schedule-changed'));
 };
 view.querySelectorAll('[data-group]').forEach(button=>button.onclick=()=>{group=button.dataset.group;render();});function syncDate(){const chosen=dateInput.value;if(!chosen)return;const [y,m,d]=chosen.split('-');document.querySelector('#year').value=y;document.querySelector('#month').value=Number(m);document.querySelector('#half').value=Number(d)<=15?'1':'2';document.querySelector('#generate').click();dateInput.value=chosen;render();}dateInput.onchange=syncDate;for(const [id,delta] of [['day-prev',-1],['day-next',1]])view.querySelector('#'+id).onclick=()=>{const d=new Date(dateInput.value+'T12:00:00');d.setDate(d.getDate()+delta);dateInput.value=localDate(d);syncDate();};view.querySelector('#day-today').onclick=()=>{dateInput.value=localDate(new Date());syncDate();};view.querySelector('#toggle-grid').onclick=e=>{grid.hidden=!grid.hidden;e.currentTarget.textContent=grid.hidden?'Ver grade da quinzena':'Ocultar grade';};document.querySelector('#generate').addEventListener('click',()=>{dateInput.value=`${document.querySelector('#year').value}-${String(document.querySelector('#month').value).padStart(2,'0')}-${document.querySelector('#half').value==='1'?'01':'16'}`;render();});document.addEventListener('rt-schedule-changed',render);document.addEventListener('rt-data-restored',render);document.addEventListener('rt-select-shift',event=>{group=event.detail>=14?'cinderella':event.detail>=7?'night':'day';render();});document.addEventListener('rt-open-date',event=>{dateInput.value=event.detail;syncDate();});syncDate();
}
